#!/usr/bin/env python3
"""
Full analysis pipeline for cryptic IP binding site validation.
Parses fpocket results, computes FreeSASA, analyzes electrostatics,
and produces a composite score for all validation structures.

Author: Tommaso Marena (generated by computational pipeline)
"""

import os
import re
import json
import csv
import math
import numpy as np
from pathlib import Path
from collections import defaultdict

try:
    import freesasa
except ImportError:
    freesasa = None

from Bio.PDB import PDBParser, NeighborSearch
from Bio.PDB.DSSP import dssp_dict_from_pdb_file


# ─── Configuration ───────────────────────────────────────────────────────
PROJ = Path(__file__).resolve().parent.parent

# Known IP-binding residue positions (from crystal structures)
KNOWN_IP_RESIDUES = {
    'ADAR2_crystal': {
        'chain': 'A',
        'residues': [376, 519, 522, 651, 672, 687],  # K376, K519, R522, R651, K672, W687
        'ip_type': 'IP6',
        'category': 'positive',
        'description': 'ADAR2 buried IP6 (PDB 1ZY7)',
    },
    'ADAR2_alphafold': {
        'chain': 'A',
        'residues': [376, 519, 522, 651, 672, 687],
        'ip_type': 'IP6',
        'category': 'positive',
        'description': 'ADAR2 AlphaFold (AF-P78563-F1)',
    },
    'Pds5B_crystal': {
        'chain': 'A',
        'residues': [1059, 1060, 1086, 1131, 1132],  # Approximate from 5HDT
        'ip_type': 'IP6',
        'category': 'positive',
        'description': 'Pds5B cohesin regulator (PDB 5HDT)',
    },
    'HDAC1_crystal': {
        'chain': 'A',
        'residues': [29, 31, 36, 270, 271],  # Approximate from 5ICN
        'ip_type': 'IP4',
        'category': 'positive',
        'description': 'HDAC1 deacetylase (PDB 5ICN)',
    },
    'HDAC3_crystal': {
        'chain': 'A',
        'residues': [29, 31, 36, 265, 266],  # Approximate from 4A69
        'ip_type': 'IP4',
        'category': 'positive',
        'description': 'HDAC3 deacetylase (PDB 4A69)',
    },
    'PLCd1_PH': {
        'chain': 'A',
        'residues': [30, 32, 36, 40, 51, 55],  # PH domain IP3-binding residues
        'ip_type': 'IP3',
        'category': 'negative',
        'description': 'PLCδ1 PH domain (PDB 1MAI)',
    },
    'Btk_PH': {
        'chain': 'A',
        'residues': [12, 28, 29, 33],  # Btk PH domain IP4 residues
        'ip_type': 'IP4',
        'category': 'negative',
        'description': 'Btk PH domain (PDB 1BTK)',
    },
    'DAPP1_PH': {
        'chain': 'A',
        'residues': [17, 19, 36, 73],  # DAPP1/PHISH PH domain
        'ip_type': 'IP4',
        'category': 'negative',
        'description': 'DAPP1 PH domain (PDB 1FAO)',
    },
    'Grp1_PH': {
        'chain': 'A',
        'residues': [267, 271, 273, 276, 280, 303],  # Grp1 PH domain
        'ip_type': 'IP4',
        'category': 'negative',
        'description': 'Grp1 PH domain (PDB 1FGY)',
    },
}

BASIC_RESIDUES = {'ARG', 'LYS', 'HIS'}


def parse_fpocket_info(info_file):
    """Parse fpocket pocket_info.txt for pocket descriptors."""
    pockets = []
    current = {}
    
    with open(info_file) as f:
        for line in f:
            line = line.strip()
            if line.startswith('Pocket'):
                if current:
                    pockets.append(current)
                pocket_num = int(re.search(r'Pocket\s+(\d+)', line).group(1))
                current = {'pocket_num': pocket_num}
            elif ':' in line and current:
                key, val = line.split(':', 1)
                key = key.strip()
                val = val.strip()
                # Parse numeric values
                try:
                    val = float(val)
                except ValueError:
                    pass
                current[key] = val
    
    if current:
        pockets.append(current)
    
    return pockets


def parse_fpocket_pdb(pocket_pdb_path):
    """Parse pocket PDB file to extract alpha-sphere centers and pocket residues."""
    atoms = []
    residues = set()
    
    with open(pocket_pdb_path) as f:
        for line in f:
            if line.startswith('ATOM') or line.startswith('HETATM'):
                x = float(line[30:38])
                y = float(line[38:46])
                z = float(line[46:54])
                resname = line[17:20].strip()
                chain = line[21]
                resseq = int(line[22:26])
                atoms.append((x, y, z))
                if resname not in ('STP',):  # STP = alpha sphere
                    residues.add((chain, resseq, resname))
                    
    if atoms:
        center = np.mean(atoms, axis=0)
    else:
        center = np.array([0, 0, 0])
        
    return center, residues, atoms


def parse_fpocket_pocket_atoms(pocket_atm_file):
    """Parse pocket atoms file to get lining residues."""
    residues = set()
    with open(pocket_atm_file) as f:
        for line in f:
            if line.startswith('ATOM'):
                chain = line[21]
                resseq = int(line[22:26])
                resname = line[17:20].strip()
                residues.add((chain, resseq, resname))
    return residues


def compute_sasa_per_residue(pdb_path):
    """Compute per-residue SASA using freesasa Python bindings."""
    if freesasa is None:
        return {}
    
    try:
        structure = freesasa.Structure(pdb_path)
        result = freesasa.calc(structure)
        
        sasa_dict = {}
        # Get per-residue SASA
        areas = freesasa.selectArea(
            ['all, all',],
            structure,
            result
        )
        
        # Parse per-atom for residue-level aggregation
        residue_sasa = defaultdict(float)
        for i in range(structure.nAtoms()):
            chain = structure.chainLabel(i)
            resnum = int(structure.residueNumber(i))
            resname = structure.residueName(i)
            atom_sasa = result.atomArea(i)
            residue_sasa[(chain, resnum, resname)] += atom_sasa
        
        return dict(residue_sasa)
    except Exception as e:
        print(f"  SASA error for {pdb_path}: {e}")
        return {}


def compute_pocket_depth(pocket_center, protein_atoms, surface_atoms=None):
    """
    Estimate pocket depth as distance from pocket center to nearest surface point.
    Approximation: distance from pocket center to the protein centroid minus 
    the average radius.
    """
    if len(protein_atoms) == 0:
        return 0.0
    
    coords = np.array([(a.get_vector().get_array()) for a in protein_atoms])
    centroid = np.mean(coords, axis=0)
    
    # Distance from pocket center to centroid
    dist_to_centroid = np.linalg.norm(pocket_center - centroid)
    
    # Approximate protein radius
    radii = np.linalg.norm(coords - centroid, axis=1)
    mean_radius = np.mean(radii)
    max_radius = np.max(radii)
    
    # Minimum distance from pocket center to any surface atom
    dists_to_atoms = np.linalg.norm(coords - pocket_center, axis=1)
    min_dist = np.min(dists_to_atoms)
    
    # Depth estimate: how far the pocket is from the nearest surface
    # A deeply buried pocket has a large distance from the surface shell
    # Surface shell is approximately at mean_radius from centroid
    depth = mean_radius - np.linalg.norm(pocket_center - centroid)
    
    # Alternatively, use the minimum distance to the convex hull boundary
    # Simplified: use fraction of distance into the protein
    if max_radius > 0:
        burial_fraction = 1.0 - (np.linalg.norm(pocket_center - centroid) / max_radius)
        depth = burial_fraction * max_radius * 2  # Scale to Angstroms
    
    return max(0, depth)


def count_basic_residues_near_pocket(pocket_center, structure, chain_id, radius=5.0):
    """Count basic residues (R, K, H) within radius Å of pocket center."""
    all_atoms = list(structure.get_atoms())
    ns = NeighborSearch(all_atoms)
    
    nearby = ns.search(pocket_center, radius, level='R')
    
    basic_count = 0
    basic_residues = []
    for residue in nearby:
        if residue.get_resname() in BASIC_RESIDUES:
            basic_count += 1
            basic_residues.append(
                f"{residue.get_resname()}{residue.get_id()[1]}"
            )
    
    return basic_count, basic_residues


def compute_local_charge_density(pocket_center, structure, radius=8.0):
    """
    Compute local charge density as a proxy for electrostatic potential.
    Sum of formal charges of residues within radius of pocket center.
    Positive = lots of basic residues, negative = lots of acidic.
    """
    CHARGE_MAP = {
        'ARG': +1, 'LYS': +1, 'HIS': +0.5,  # His partially protonated at pH 7
        'ASP': -1, 'GLU': -1,
    }
    
    all_atoms = list(structure.get_atoms())
    ns = NeighborSearch(all_atoms)
    nearby = ns.search(pocket_center, radius, level='R')
    
    total_charge = 0.0
    for residue in nearby:
        resname = residue.get_resname()
        if resname in CHARGE_MAP:
            total_charge += CHARGE_MAP[resname]
    
    return total_charge


def find_best_pocket_for_known_site(fpocket_dir, known_info, structure_path):
    """
    For a structure with known IP-binding residues, find the fpocket pocket
    that best overlaps with the known site.
    """
    pockets_dir = os.path.join(fpocket_dir, 'pockets')
    if not os.path.exists(pockets_dir):
        return None, 0
    
    known_residues = set(known_info['residues'])
    known_chain = known_info['chain']
    
    pocket_files = sorted([f for f in os.listdir(pockets_dir) if f.endswith('_atm.pdb')])
    
    best_pocket = None
    best_overlap = 0
    best_pocket_num = 0
    
    for pf in pocket_files:
        pocket_num = int(re.search(r'pocket(\d+)', pf).group(1))
        pocket_residues = parse_fpocket_pocket_atoms(os.path.join(pockets_dir, pf))
        
        # Count overlap with known IP-binding residues
        pocket_resnums = {resseq for chain, resseq, resname in pocket_residues}
        overlap = len(known_residues & pocket_resnums)
        
        if overlap > best_overlap:
            best_overlap = overlap
            best_pocket = pf
            best_pocket_num = pocket_num
    
    return best_pocket_num, best_overlap


def compute_composite_score(depth, sasa, charge, basic_count,
                            w_depth=0.30, w_sasa=0.35, w_elec=0.20, w_basic=0.15):
    """
    Compute the composite burial score for a pocket.
    
    Score = w_depth * norm(depth) + w_sasa * (1 - norm(sasa)) + w_elec * norm(charge) + w_basic * norm(basic)
    
    Normalization:
    - depth: cap at 30 Å
    - sasa: cap at 50 Å² (inverted: low SASA = high score)
    - charge: cap at 15 (charge units)
    - basic: cap at 8
    """
    norm_depth = min(depth / 30.0, 1.0)
    norm_sasa = 1.0 - min(sasa / 50.0, 1.0)  # Inverted: low SASA = high score
    norm_charge = min(max(charge, 0) / 15.0, 1.0)
    norm_basic = min(basic_count / 8.0, 1.0)
    
    score = (w_depth * norm_depth +
             w_sasa * norm_sasa +
             w_elec * norm_charge +
             w_basic * norm_basic)
    
    return score, {
        'norm_depth': norm_depth,
        'norm_sasa': norm_sasa,
        'norm_charge': norm_charge,
        'norm_basic': norm_basic,
    }


def analyze_structure(name, info):
    """Run full analysis for one structure."""
    cleaned_dir = PROJ / 'data' / 'cleaned'
    fpocket_dir = PROJ / 'data' / 'fpocket_results' / f'{name}_out'
    pdb_path = cleaned_dir / f'{name}.pdb'
    
    if not pdb_path.exists():
        return None
    
    print(f"\n{'='*60}")
    print(f"Analyzing: {name} — {info['description']}")
    print(f"{'='*60}")
    
    result = {
        'name': name,
        'category': info['category'],
        'description': info['description'],
        'ip_type': info['ip_type'],
    }
    
    # 1. Parse structure
    parser = PDBParser(QUIET=True)
    structure = parser.get_structure(name, str(pdb_path))
    model = structure[0]
    
    # Total atoms and residues
    all_residues = list(model.get_residues())
    all_atoms = list(model.get_atoms())
    result['total_residues'] = len(all_residues)
    result['total_atoms'] = len(all_atoms)
    print(f"  Structure: {result['total_atoms']} atoms, {result['total_residues']} residues")
    
    # 2. Count total pockets from fpocket
    pockets_dir = fpocket_dir / 'pockets'
    if pockets_dir.exists():
        pocket_files = [f for f in os.listdir(pockets_dir) if f.endswith('_atm.pdb')]
        result['total_pockets'] = len(pocket_files)
    else:
        result['total_pockets'] = 0
    print(f"  Pockets detected: {result['total_pockets']}")
    
    # 3. Find the pocket that best matches known IP-binding site
    best_pocket_num, overlap = find_best_pocket_for_known_site(
        str(fpocket_dir), info, str(pdb_path))
    result['best_pocket_num'] = best_pocket_num
    result['ip_site_residue_overlap'] = overlap
    result['ip_site_rank'] = best_pocket_num  # fpocket ranks by druggability
    print(f"  Best matching pocket: #{best_pocket_num} (overlap: {overlap}/{len(info['residues'])} residues)")
    
    # 4. Get pocket center and lining residues
    if best_pocket_num > 0:
        pocket_atm_file = pockets_dir / f'pocket{best_pocket_num}_atm.pdb'
        if pocket_atm_file.exists():
            pocket_residues = parse_fpocket_pocket_atoms(str(pocket_atm_file))
            result['pocket_lining_residues'] = len(pocket_residues)
            
            # Calculate pocket center from atoms file
            atoms_coords = []
            with open(pocket_atm_file) as f:
                for line in f:
                    if line.startswith('ATOM'):
                        x = float(line[30:38])
                        y = float(line[38:46])
                        z = float(line[46:54])
                        atoms_coords.append([x, y, z])
            pocket_center = np.mean(atoms_coords, axis=0) if atoms_coords else np.zeros(3)
        else:
            pocket_center = np.zeros(3)
            result['pocket_lining_residues'] = 0
    else:
        pocket_center = np.zeros(3)
        result['pocket_lining_residues'] = 0
    
    # 5. SASA analysis
    print("  Computing SASA...")
    sasa_dict = compute_sasa_per_residue(str(pdb_path))
    
    if sasa_dict:
        # Get SASA for known IP-binding residues
        ip_sasa_values = []
        for resnum in info['residues']:
            for (chain, rnum, rname), sasa_val in sasa_dict.items():
                if rnum == resnum:
                    ip_sasa_values.append(sasa_val)
                    break
        
        if ip_sasa_values:
            result['ip_site_mean_sasa'] = np.mean(ip_sasa_values)
            result['ip_site_min_sasa'] = np.min(ip_sasa_values)
            result['ip_site_max_sasa'] = np.max(ip_sasa_values)
            result['ip_site_total_sasa'] = np.sum(ip_sasa_values)
        else:
            result['ip_site_mean_sasa'] = 0
            result['ip_site_min_sasa'] = 0
            result['ip_site_max_sasa'] = 0
            result['ip_site_total_sasa'] = 0
        
        # Overall pocket SASA
        if best_pocket_num > 0 and pocket_residues:
            pocket_sasa_values = []
            for (chain, resseq, resname) in pocket_residues:
                for (sc, sr, sn), sv in sasa_dict.items():
                    if sr == resseq:
                        pocket_sasa_values.append(sv)
                        break
            if pocket_sasa_values:
                result['pocket_mean_sasa'] = np.mean(pocket_sasa_values)
            else:
                result['pocket_mean_sasa'] = 0
        else:
            result['pocket_mean_sasa'] = 0
        
        print(f"  IP-site mean SASA: {result['ip_site_mean_sasa']:.2f} Å²")
        print(f"  Pocket mean SASA: {result.get('pocket_mean_sasa', 0):.2f} Å²")
    else:
        result['ip_site_mean_sasa'] = 0
        result['pocket_mean_sasa'] = 0
        print("  SASA: could not compute (freesasa unavailable)")
    
    # 6. Basic residue count near pocket
    basic_count, basic_list = count_basic_residues_near_pocket(
        pocket_center, model, info['chain'], radius=5.0)
    result['basic_residues_5A'] = basic_count
    result['basic_residue_list'] = basic_list
    print(f"  Basic residues within 5Å: {basic_count} ({', '.join(basic_list[:8])})")
    
    # Also count at 8Å
    basic_count_8, _ = count_basic_residues_near_pocket(
        pocket_center, model, info['chain'], radius=8.0)
    result['basic_residues_8A'] = basic_count_8
    
    # 7. Local charge density (electrostatics proxy)
    charge = compute_local_charge_density(pocket_center, model, radius=8.0)
    result['local_charge_8A'] = charge
    print(f"  Local charge density (8Å): {charge:+.1f}")
    
    # 8. Pocket depth estimate
    depth = compute_pocket_depth(pocket_center, all_atoms)
    result['pocket_depth_estimate'] = depth
    print(f"  Pocket depth estimate: {depth:.1f} Å")
    
    # 9. Composite score
    sasa_for_score = result.get('ip_site_mean_sasa', result.get('pocket_mean_sasa', 25))
    score, components = compute_composite_score(
        depth=depth,
        sasa=sasa_for_score,
        charge=max(charge, 0),
        basic_count=basic_count
    )
    result['composite_score'] = score
    result['score_components'] = components
    print(f"  COMPOSITE SCORE: {score:.4f}")
    print(f"    depth={components['norm_depth']:.3f}  sasa={components['norm_sasa']:.3f}  "
          f"charge={components['norm_charge']:.3f}  basic={components['norm_basic']:.3f}")
    
    # 10. Parse fpocket descriptors for the best pocket
    info_file = fpocket_dir / f'{name}_info.txt'
    if info_file.exists():
        all_pockets_info = parse_fpocket_info(str(info_file))
        for pi in all_pockets_info:
            if pi.get('pocket_num') == best_pocket_num:
                result['fpocket_score'] = pi.get('Score', 0)
                result['fpocket_druggability'] = pi.get('Druggability Score', 0)
                result['fpocket_volume'] = pi.get('Real volume (Monte Carlo)', 0)
                result['fpocket_hydrophobicity'] = pi.get('Hydrophobicity score', 0)
                result['fpocket_polarity'] = pi.get('Polarity score', 0)
                break
    
    return result


def main():
    results = []
    
    for name, info in KNOWN_IP_RESIDUES.items():
        r = analyze_structure(name, info)
        if r is not None:
            results.append(r)
    
    # ─── Save results as JSON ───────────────────────────────────────────
    results_dir = PROJ / 'results'
    results_dir.mkdir(exist_ok=True)
    
    # Full JSON
    with open(results_dir / 'validation_results.json', 'w') as f:
        # Convert numpy types
        def convert(obj):
            if isinstance(obj, (np.integer,)): return int(obj)
            if isinstance(obj, (np.floating,)): return float(obj)
            if isinstance(obj, np.ndarray): return obj.tolist()
            return obj
        
        json.dump(results, f, indent=2, default=convert)
    
    # ─── Summary CSV ────────────────────────────────────────────────────
    csv_fields = [
        'name', 'category', 'description', 'ip_type',
        'total_residues', 'total_pockets', 'ip_site_rank',
        'ip_site_residue_overlap', 'ip_site_mean_sasa',
        'pocket_mean_sasa', 'basic_residues_5A', 'basic_residues_8A',
        'local_charge_8A', 'pocket_depth_estimate', 'composite_score',
    ]
    
    with open(results_dir / 'validation_summary.csv', 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=csv_fields, extrasaction='ignore')
        writer.writeheader()
        for r in results:
            writer.writerow({k: (f'{v:.4f}' if isinstance(v, float) else v) for k, v in r.items() if k in csv_fields})
    
    # ─── Print summary table ────────────────────────────────────────────
    print("\n\n" + "="*100)
    print("VALIDATION SUMMARY")
    print("="*100)
    print(f"{'Name':<22} {'Cat':<5} {'Rank':<6} {'SASA':<10} {'Basic5':<7} {'Charge':<8} {'Depth':<8} {'Score':<8}")
    print("-"*100)
    
    for r in sorted(results, key=lambda x: -x['composite_score']):
        cat = '+' if r['category'] == 'positive' else '-'
        print(f"{r['name']:<22} {cat:<5} "
              f"{r['ip_site_rank']:<6} "
              f"{r['ip_site_mean_sasa']:>8.2f}  "
              f"{r['basic_residues_5A']:>5}  "
              f"{r['local_charge_8A']:>+6.1f}  "
              f"{r['pocket_depth_estimate']:>6.1f}  "
              f"{r['composite_score']:>6.4f}")
    
    print("\n" + "="*100)
    print("KEY: Cat = category (+ = positive/buried, - = negative/surface)")
    print("     Rank = fpocket pocket number matching known IP site")
    print("     SASA = mean SASA of known IP-coordinating residues (Å²)")
    print("     Basic5 = basic residues within 5Å of pocket center")
    print("     Charge = net formal charge within 8Å")
    print("     Depth = estimated pocket depth (Å)")
    print("     Score = composite burial score (0–1)")
    print("="*100)
    
    # ─── Statistical comparison ─────────────────────────────────────────
    pos = [r for r in results if r['category'] == 'positive']
    neg = [r for r in results if r['category'] == 'negative']
    
    print(f"\nPositive controls (n={len(pos)}):")
    print(f"  Mean composite score: {np.mean([r['composite_score'] for r in pos]):.4f} "
          f"± {np.std([r['composite_score'] for r in pos]):.4f}")
    print(f"  Mean SASA:            {np.mean([r['ip_site_mean_sasa'] for r in pos]):.2f} "
          f"± {np.std([r['ip_site_mean_sasa'] for r in pos]):.2f} Å²")
    print(f"  Mean basic (5Å):      {np.mean([r['basic_residues_5A'] for r in pos]):.1f} "
          f"± {np.std([r['basic_residues_5A'] for r in pos]):.1f}")
    
    print(f"\nNegative controls (n={len(neg)}):")
    print(f"  Mean composite score: {np.mean([r['composite_score'] for r in neg]):.4f} "
          f"± {np.std([r['composite_score'] for r in neg]):.4f}")
    print(f"  Mean SASA:            {np.mean([r['ip_site_mean_sasa'] for r in neg]):.2f} "
          f"± {np.std([r['ip_site_mean_sasa'] for r in neg]):.2f} Å²")
    print(f"  Mean basic (5Å):      {np.mean([r['basic_residues_5A'] for r in neg]):.1f} "
          f"± {np.std([r['basic_residues_5A'] for r in neg]):.1f}")
    
    # Effect size (Cohen's d)
    pos_scores = [r['composite_score'] for r in pos]
    neg_scores = [r['composite_score'] for r in neg]
    pooled_std = np.sqrt((np.var(pos_scores) + np.var(neg_scores)) / 2)
    if pooled_std > 0:
        cohens_d = (np.mean(pos_scores) - np.mean(neg_scores)) / pooled_std
    else:
        cohens_d = float('inf')
    print(f"\nScore separation (Cohen's d): {cohens_d:.2f}")
    
    # Mann-Whitney U test
    from scipy import stats
    if len(pos_scores) >= 2 and len(neg_scores) >= 2:
        u_stat, p_val = stats.mannwhitneyu(pos_scores, neg_scores, alternative='greater')
        print(f"Mann-Whitney U test: U={u_stat:.1f}, p={p_val:.6f}")
    
    print("\nResults saved to:")
    print(f"  {results_dir / 'validation_results.json'}")
    print(f"  {results_dir / 'validation_summary.csv'}")


if __name__ == '__main__':
    main()
